[env]
TERM = "xterm-256color"
working_directory = "/Users/woot/CodeProject"

# Colors (Iceberg Dark)
[colors]
# Default colors
[colors.primary]
background = '#161821'
foreground = '#d2d4de'

# Normal colors
[colors.normal]
black    = '#161821'
red      = '#e27878'
green    = '#b4be82'
yellow   = '#e2a478'
blue     = '#84a0c6'
magenta  = '#a093c7'
cyan     = '#89b8c2'
white    = '#c6c8d1'

# Bright colors
[colors.bright]
black    = '#6b7089'
red      = '#e98989'
green    = '#c0ca8e'
yellow   = '#e9b189'
blue     = '#91acd1'
magenta  = '#ada0d3'
cyan     = '#95c4ce'
white    = '#d2d4de'

[font]
normal = { family = 'PragmataPro', style = 'Regular' }
size     = 21.0

[scrolling]
history = 10000
multiplier = 3

[window]
startup_mode = 'Fullscreen'
decorations = 'buttonless'
position = { x = 0, y = 0 }

